;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-mouse-drag-region
        evil-next-visual-line
        evil-previous-visual-line
        mc/toggle-cursor-on-click
        ))

(setq mc/cmds-to-run-once
      '(
        ))
